
import SmoothScroll from "@/components/scroll/SmoothScroll";
import "./globals.css";
import Header from "@/components/header/Header";
import LenisScroll from "@/components/scroll/LenisScroll";
import Footer from "@/components/footer/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <LenisScroll>
          <Header />
          {children}
        </LenisScroll>
      </body>
    </html>
  );
}
